name: Pull request
on: 
  pull_request:
    branches:
      - develop
jobs:
  test:
    runs-on: macos-10.15
    timeout-minutes: 15
    steps:
      - name: Cancel previous jobs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
      - name: Git - Checkout
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.ref }}
      - name: Setup - Xcode
        run: sudo xcode-select -s /Applications/Xcode_13.2.1.app
      - name: Setup - Ruby and bundler dependencies
        uses: ruby/setup-ruby@v1.57.0
        with:
          ruby-version: 2.4.0
          bundler-cache: true
      - name: Test - Fastlane tests
        run: bundle exec fastlane test
